### ISSUE TITLE
[코드 리뷰] by store2

### ISSUE THREAD

**Issue by negu63** [woowa-techcamp-2021/store-1#18]
### 리뷰 링크

https://github.com/woowa-techcamp-2021/store-1/pull/15#discussion_r688271142

https://github.com/woowa-techcamp-2021/store-1/pull/5#pullrequestreview-729299271

https://github.com/woowa-techcamp-2021/store-1/pull/2#issuecomment-898227265 

도커 굉장히 인상적이네요 꼭 써봐야겠어요 ㅎㅎ
잘 보고 갑니다 ~ 화이팅!!!

**Comment by yoonminsang** [comment]
https://github.com/woowa-techcamp-2021/store-1/pull/9#discussion_r688267903
https://github.com/woowa-techcamp-2021/store-1/pull/14#discussion_r688272358
https://github.com/woowa-techcamp-2021/store-1/pull/14#discussion_r688280110

**Comment by Seogeurim** [comment]
### 서그림

[#7 (comment)](https://github.com/woowa-techcamp-2021/store-1/pull/11#discussion_r688269028)

[#7 (comment)](https://github.com/woowa-techcamp-2021/store-1/pull/11#discussion_r688269745)

[#7 (comment)](https://github.com/woowa-techcamp-2021/store-1/pull/11#discussion_r688269911)

[#12 (comment)](https://github.com/woowa-techcamp-2021/store-1/pull/12#discussion_r688272572)
