### ISSUE TITLE
[feature] 스타일드 컴포넌트 만들기

### ISSUE THREAD

**Issue by cothis** [woowa-techcamp-2021/store-1#20]
## :hammer: 기능 설명

스타일드 컴포넌트를 만들어봅시다..

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] 체크 사항 1
- [ ] 체크 사항 2
- [ ] 체크 사항 3
- [ ] 체크 사항 4

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

## 🕰 예상 시간

> 1 md

**Comment by CurlyBat** [comment]
https://blog.slashuniverse.com/m/8?category=993311

기본적인 tagged template literal 및 기본 기능 구현(ThemeProvider같은 부분 제외)용 참고자료
