### ISSUE TITLE
[docs] .gitmessage

### ISSUE THREAD

**Issue by CurlyBat** [woowa-techcamp-2021/store-1#21]
## :hammer: 기능 설명

.gitmessage co author update

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] co author 추가

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

없음

## 🕰 예상 시간

> 1 mm

**Comment by TsooranKim** [comment]
앗! 빠르세요 ㅎㅎ
