### ISSUE TITLE
[feature] 자동배포 시 build:force 수행 및 workflow 수정

### ISSUE THREAD

**Issue by cothis** [woowa-techcamp-2021/store-1#63]
## :hammer: 기능 설명

build force 넣었던게 빠져있어서 넣겠습니다.
그리고 pull request만 해도 배포를 시도하고 있어서 그부분 수정하겠습니다.

## 🕰 예상 시간

> 1 mh

**Comment by TsooranKim** [comment]
build:force 말고 뭔가 다른 이름이면 좋겠습니다.
force라고 해도 어차피 webpack에서 터지면 터지는거라 force가 아니라서요.
