### ISSUE TITLE
10팀 코드 리뷰

### ISSUE THREAD

**Issue by Kyun2da** [woowa-techcamp-2021/store-1#72]
10팀 코드 리뷰

**Comment by KangyeolLee** [comment]
많은 걸 배워갑니다~~


[무야호](https://github.com/woowa-techcamp-2021/store-1/pull/9#pullrequestreview-734687367)
[무얏호](https://github.com/woowa-techcamp-2021/store-1/pull/11#discussion_r692683441)
[이야호](https://github.com/woowa-techcamp-2021/store-1/pull/12#pullrequestreview-734693896)


이만 3시 세미나 참여로 인해 총총..

**Comment by HanCheo** [comment]
(홀리몰리 : #12)[https://github.com/woowa-techcamp-2021/store-1/pull/12#pullrequestreview-734688085]
(모홀리리 : #9)[https://github.com/woowa-techcamp-2021/store-1/pull/9#pullrequestreview-734691963]
(홓홓호 : #14)[https://github.com/woowa-techcamp-2021/store-1/pull/14]
